_target_: orgflow.model.arch.CSPNet
hidden_dim: 128
time_dim: 256
num_layers: 12 # Testing more layers for organic data
act_fn: silu
dis_emb: sin
num_freqs: 128
edge_style: custom
max_neighbors: 10
cutoff: 5.
ln: true
use_log_map: false  # false would put it in line with DiffCSP (euclidean distance function)
dim_atomic_rep: ${get_dim_atomic_rep:${model.manifold_getter.atom_type_manifold}}
lattice_manifold: ${model.manifold_getter.lattice_manifold}
concat_sum_pool: true
represent_num_atoms: false
represent_angle_edge_to_lattice: true
self_edges: false
self_cond: ${model.self_cond}
